larpix/larpix-control

scripts/larpix-drivercheck-mac
scripts/larpix-drivercheck-ubuntu
scripts/larpix-find-device-mac
scripts/larpix-find-device-ubuntu
setup.py

I created 4 scripts: 2 for Mac and 2 for Ubuntu/Debian Linux. Therre's a script which verifies the FTDI driver is installed (`larpix-drivercheck-*`) and a script which finds the correct `/dev/xxxx` port to connect to (`larpix-find-device-*`). This would complete Issue #11

Add scripts to help with interfacing with the FTDI chip

---

larpix/larpix.py
test/test_larpix.py

This PR creates a bunch of "export" methods, the end result of which is to allow `Controller.save_output` to save all of the output collected in each chip's `reads` list into a JSON file. As a bonus I included the appropriate unit tests and docstrings for each of the new methods I created.

Export data to disk

---

larpix/benchtest.py

Add a periodic reset test which iterates through a wide range of periodic reset intervals and expects data to be triggered by an external trigger.
Add a `--verbose` option to the command line to include debug statements in the log.
Add a `-m` option to include a custom log message along with all of the automatically-logged messages.

Bench test additions: periodic reset test, --verbose, and a log message

---

larpix/larpix.py
larpix/tasks.py

I made the startup routine a little more flexible. The particular configuration used to quiet the chips is specified in a JSON file in the configs module. (I picked global threshold, just as before.) If we pick another way we want to bring up the chips, we can just change the JSON file.
I also changed the method for determining chip IDs. Instead of involving actual ADC data flow, I just attempt to read the configuration of each possible chip. Any result that comes back with the correct (expected) configuration indicates that the corresponding chip exists in the daisy chain.
I also updated both methods to use the same method structure as in benctest, passing in a dict of settings and utilizing the logger module.

Revise startup tasks: initial configuration (quiet) and identifying chip IDs

---

larpix/larpix.py
test/test_larpix.py

The `chip.sync_configuration` method goes through `chip.reads` in chronological order and finds all of the configurations that have been read out. The most recent read is saved for each configuration register. Then the values from those configuration registers are used to update the attributes of `chip.config`.
Assisting in this effort is a set of private attributes of the Configuration object, which specify how to update the appropriate attributes given a particular register number and the data stored in that register.

Update Configuration object based on actual config read packets

---

larpix/larpix.py
test/test_larpix.py

Inspired by #34, I wrote a class to manage groups of packets, called `PacketCollection`. The idea is that each call to `controller.run` would create a PacketCollection with the packets that were read in during the run.
Please take a look ( @peter-madigan @dadwyer ) and comment if you'd like. I'm still working on it. This isn't (yet) a request to merge. But probably will be in a day or 2.
PacketCollections have a bunch of responsibilities and functionalities, including
I have not yet decided how to handle the following:
- timestamps: it is trivial to save the CPU timestamp at the start and/or end of a read, but that does not help us with the time of individual packet arrivals. To get this working the right way, we might have to handle #53 (sending commands during a serial read).
- …

PacketCollections: the solution to read history and to controller.reads

---

larpix/simulation.py
test/test_larpix.py
test/test_simulation.py

The new ``larpix.simulation`` module allows for easy simulations of the control software. It hooks right in to the existing software via the call ``controller._serial = simulation.model(chips)``. After that, configuration writes and reads work as expected, updating the mock chip's configuration registers and reading them out as packets to the controller.
The configuration registers don't actually do anything yet to affect the chip's behavior, except for the CSA gain, which was easy to program in to the trigger functionality. Right now, the only behavior for the chips is to trigger at random times on a random channel with a charge of 1e5 electrons. I'll need to do more work for that.
Even though the module is not complete, it is still worth testing out with new scripts to make sure the …

Basic LArPix simulation

---

larpix/larpix.py
larpix/tasks.py
test/test_larpix.py

Improve configuration_read and configuration_write by allowing a specific order of registers (#52), and allowing for a log message to be saved to the ``PacketCollection`` (#59)
Update ``larpix.tasks.get_chip_ids`` to handle ``PacketCollection``s (and also more gracefully handle problems involving too many or too few packets received) (#63)

Resolve some quick/easy issues

---

larpix/larpix.py
test/test_larpix.py

In particular, if the output is an array with only a few (<5) changes,
just describe each changed array element rather than printing out the
entire array.
Fixes #50

Update config.get_nondefault_registers to shorter output

---

larpix/larpix.py
larpix/tasks.py
test/test_larpix.py

Controller objects now have controller.chips (to be populated manually) and controller.all_chips (initialized with object creation using what used to be controller.init_chips and is now controller._init_chips).
Fixes #48

Split up the idea of "active chips" from "all possible chips"

---

larpix/larpix.py
test/test_larpix.py

Fix #73 by using 'raw_unicode_escape' encoding
This converts between bytes objects and str objects by taking every
character literally, i.e. b'\<whatever\>' <-> '\<whatever\>'.

Change encoding so we can save bytestreams to JSON files without crashing

---

larpix/larpix.py
test/test_larpix.py

Adds get_packet_attr to PacketCollection to solve issue #72 
Usage:
` collection.get_packet_attr('adc_counts', chipid=246)`
returns a list of the `adc_counts` values for packets with `chipid == 246`.
Known issue:
~~This does not check for packet type, so this will return `packet.dataword` for all packets (not just data packets). The quick fix is just to call `collection.get_packet_attr('dataword', packet_type=Packet.DATA_PACKET)`.~~ Fixed by switching to dict representation of packets.

PacketCollection shortcut

---

larpix/larpix.py
larpix/tasks.py
test/test_larpix.py

Add new functions, Controller.multi_read_configuration and Controller.multi_write_configuration. This forms a single bytestream with all the desired configuration commands to send out all at once, eliminating the need for repeated calls to write_configuration or read_configuration (which involves many reads/writes and serial port open/close).

Read and write configurations to/from multiple chips in one serial call

---

larpix/larpix.py
larpix/simulation.py
test/test_larpix.py

Issue #23 points out that when there are parsing problems, the problematic bytes are silently discarded. This PR updates ``parse_input`` to return a tuple ``(packets, skipped)``, where ``skipped`` is itself a list of tuples of the form ``(slice(start, end), b'whatever-was-skipped')``. (The slice specifies the location of the skipped bytes in the original bytestring.)
So for standalone calls to ``parse_input``, the skipped bytes can be inspected. For all instances within the library where ``parse_input`` is called, the skipped bytes are added as an attribute to the PacketCollection that stores all of the packets from the particular larpix read.
Fixes #23

Store bytes that caused parsing problems

---

dat2h5.py
larpix/Timestamp.py
larpix/datalogger.py
larpix/larpix.py
test/test_larpix.py

Updates the Timestamp algorithm to better handle ambiguous timestamps.
Update the Timestamp serialization conditions (packet must arrive <1.5s after the serial read is initiated)
Change datalogger to timestamp at start of serial read instead of at the end.

Fix bug in Timestamp

---

larpix/bitarrayhelper.py
larpix/larpix.py
setup.py
test/test_larpix.py

I replaced all uses of bitstring (``Bits`` and ``BitArray`` objects) with bitarray (``bitarray`` objects). Let's hope this speeds things up. Bitarray is written in C so should be faster…

Refactor packet code to use bitarray rather than bitstring

---

test/test_larpix.py

The "message" parameter is deprecated in pytest v4.1. The refactor is to provide an explicit failure if the exception is not raised. https://docs.pytest.org/en/stable/deprecations.html#raises-message-deprecated

Refactor tests with pytest.raises (#101)

---

larpix/io/zmq_io.py
test/test_zmq_io.py

Fixed bug that raised an error when encoding packets while using python 2.
Adds a test for encoding / decoding ZMQ IO messages.

Fix issue #119: ZMQ packet parsing for python2

---

test/test_h5_logger.py
test/test_stdout_logger.py

Fix for issue 115 - tests in logger should ignore warning related to missing IO object.

Fis issue 115: Ignore irrelevant IO warning in logger tests

---

.travis.yml
MANIFEST.in
setup.py

Removed the MANIFEST.in file in favor of the more modern and precise package_data argument to setup.py. Fixed the travis-ci testing configuration which was unable to catch this type of error because it was running ``pip install -e .`` rather than ``pip install .`` and so was not checking for copied files.

Fix issues with copying files during pip install

---

larpix/larpix.py
test/test_larpix.py

Previously there was a hardcoded ``True`` in the implementation of controller.load. That is fixed and now there is a test to catch that error.

Successfully override safe mode in controller.load

---

larpix/logger/h5_logger.py
test/test_h5_logger.py

This obviates the need for special "tempfile" handling in the h5_logger unit tests since the built-in pytest tmpdir object can be used to specify a location for the temporary file. It also might make things more convenient when we're looking for places to save the log files.
As a bonus, the temporary files are saved for 3 test cycles before they are purged, so you can examine them if the tests fail.
Fixes #139

Add directory param to HDF5Logger init

---

larpix/larpix.py

This fixes the bugs that were found in this method. I've opted to not try and do a hotfix, since this is not a commonly used method.

Issue#142: Fix bugs in read_channel_pedestal

---

docs/api/format/hdf5format.rst
docs/api/format/index.rst
docs/api/logger/index.rst
docs/index.rst
larpix/format/hdf5format.py
larpix/io/fakeio.py
larpix/larpix.py
larpix/logger/__init__.py
larpix/logger/h5_logger.py
larpix/logger/stdout_logger.py
test/test_h5_logger.py
test/test_hdf5format.py
test/test_larpix.py
test/test_stdout_logger.py

I made a module that can convert between a list of packets and an HDF5 file. The format I used is slightly different from the HDF5Logger format so I updated the HDF5Logger to match. I have checked compatibility with some example data runs.
The major change here is in handling the "global timestamp" or "record timestamp" (formerly known as "serial timestamp"). Based on Dan's comments, special timestamp packets will be inserted into the data stream. They will be saved inline with the UART packets in the HDF5 file. For now, the timestamp packets are generated in the ``Controller.run`` method (or must be generated manually in programs that manually call ``Controller.read``). Eventually they will be part of the data stream that is received by the Controller's IO object.
I was torn on whether …

HDF5 file format + TimestampPacket

---

README.md

This was a lingering holdover from migrating to larpix/larpix-control.
#148

Fix readme "docs badge" link

---

larpix/io/serialport.py

Re: #98 - no longer want to maintain the SerialPort class.

Issue DeprecationWarning when loading the serialport module

---

docs/api/format/index.rst
docs/api/logger/h5_logger.rst
larpix/format/message_format.py
larpix/io/__init__.py
larpix/io/multizmq_io.py
larpix/io/zmq_io.py
test/test_message_format.py
test/test_multizmq_io.py
test/test_zmq_io.py

@samkohn, I've implemented a reader for our new and improved "Igor dataserver format". Basically, the new format includes a header word (8-bytes) included with every transmission. The first two bytes are reserved for versioning and the third is reserved for the message type (e.g. timestamp, data, others?). The remaining bytes are particular to the message type. The message "payload" can then be any number of 8-byte words following the header (so we are not necessarily stuck with an 8-byte timestamp at this point). I've implemented this and added a basic test.
I don't think that this format significantly impacts the data rate - only one header message is sent per DAQ board fifo flush (1024 packets). So, if the data rate is high, the headers are an insignificant fraction of the data.
Since …

Issue #145 / parse new zmq data formats

---

larpix/larpix.py

Fixes #161 - ensures that Packet.export returns a JSON-serializable object.

Update Packet.export to send chip_key as a string (or None)

---

README.md
docs/api/logger/h5_logger.rst
larpix/logger/h5_logger.py
test/test_h5_logger.py
test/test_tutorial.py

Fix up some outdated descriptions, autoattribute documentation, and tutorial code and tests.
- Move ``HDF5Logger.VERSION`` (class attribute) to ``self.version`` (HDF5Logger instance attribute), defaults on initialization to ``larpix.format.hdf5format.latest_version``.
- Manually construct the ``_buffer`` object since it's not so simple to create it based on the LArPix+HDF5 ``dtype``. (Rename ``_buffer['raw_packet']`` to ``_buffer['packets']`` independent of the format version.)
- Remove the HDF5 format description from HDF5Logger. Instead, refer to the ``hdf5format`` docs.

Update HDF5Logger + docs + tutorial to LArPix+HDF5v1.0

---

README.md
larpix/io/multizmq_io.py
larpix/io/zmq_io.py

Allows for users to specify a remapping of io channels so that packets sent/received on one channel can be made to appear to arrive on another channel. This is a temporary fix for the v1.5 anode where packets sent on channel 1 are received on channel 2.

Add ability to alter the apparent channel from a given ZMQ_IO channel

---

larpix/configs/io/loopback.json
test/test_tutorial.py

Fixes #165
ZMQ hangs in context.term if
1. the socket connects to an address ending in ".local" that does not
exist
2. 5 seconds have not yet elapsed, per attempted socket connect
This seems to only be present in our test_tutorial.py script. I fixed it
by replacing the daq-srv1.json config call with a new loopback.json file
that just connects to localhost.

Fix networking bug in test_tutorial (ugh)

---

larpix/larpix.py
larpix/quickstart.py

Update quickstart.quickcontroller to work with new IO, Logger, etc.
Default configuration is now:
- ``ZMQ_IO('io/daq-srv1.json')``
- ``HDF5Logger(filename=None)``
- ``controller.load('controller/pcb-5_chip_info.json')``
- Same ASIC configuration (Global threshold = 60, internal bypass = 1,
periodic reset = 1, reset_cycles = 4096, other registers =
default/startup)
Fixes #137

Modernize quickstart

---

README.md
larpix/logger/__init__.py
larpix/logger/h5_logger.py
larpix/logger/stdout_logger.py
test/test_h5_logger.py
test/test_stdout_logger.py
test/test_tutorial.py

In particular, the enable/disable/is_enabled logic, and the init method
are now implemented in Logger.
This also involves deprecating the open/close/is_open methods, which
now raise ``DeprecationWarning``s. These methods now just edit the
``_open`` instance attribute which is never referenced in any methods.
These methods and instance attribute will be removed in the next major
version.
Tests have been updated to both "deprecated" versions and normal
versions.
The tutorial has been updated to stop referencing the open and close
methods.
Fixes #156

Refactor common Logger subclass logic into Logger class

---

larpix/larpix.py
test/test_larpix.py

Aims to address issue #175 . Bumps up chip key assignment to ~7-8us.
```python
In [1]: from larpix.larpix import Key, Packet                                   
In [2]: %timeit p = Packet(); p.chip_key=Key(1,2,3)                             
7.61 µs ± 87.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Update internal data representation of Keys

---

larpix/configs/__init__.py
larpix/configs/chip/__init__.py
larpix/configs/controller/__init__.py
larpix/controller.py
test/test_configuration.py
test/test_configuration_files.py
test/test_controller.py

Adds the optional "_include" field to configuration files which loads fields included specified files. Verifies that configuration types ("_config_type") of inherited files matches.

Add inheritances as an option for all configuration files

---

README.md
larpix/controller.py
test/test_controller.py
test/test_tutorial.py

Allows access to a list of chip keys sorted by their depth within the network structure -- useful for things like modifying the uart speed, etc. where network communications could be broken by the configuration.
Moved from PR #199

Implement network traversal in controller
