larpix/larpix.py
test/test_larpix.py

Still fails the value validation tests, but I wasn't able to quickly figure out what is going wrong. That should be solved before merging.

Implement Configure getters and setters

---

larpix/larpix.py

Implements @samkohn's suggestion -- allows for config files to just specify values that are not default.

Clean up methods for Config read/write to JSON

---

larpix/larpix.py
test/test_larpix.py

Update write_configuration with serial_read>0 to parse its input

---

larpix/configs/physics.json
scripts/internal_pulser_scan.py

Finally merging in the internal pulser scan script

Add internal pulser scan script

---

larpix/larpix.py
test/test_larpix.py

The new ``controller.load`` method will replicate the state saved in the JSON file, in particular, controller.reads, controller.chips, and controller.chips[i].reads.

Add data loader to read in JSON output files

---

larpix/larpix.py
larpix/tasks.py
test/test_larpix.py

My updates from c6fa45a did not actually completely update larpix.tasks to work.
There were also some issues on controller.sort_packets which only became apparent during this repair work.
cc: #67

Hotfix on larpix.tasks

---

test/test_larpix.py

Issue 71 fix: Test controller.read_configuration

---

larpix/tasks.py

Adds a method to larpix.tasks for generating basic histograms and ADC v. time.

Add simple_plot to larpix.tasks

---

larpix/larpix.py
larpix/quickstart.py
larpix/serialport.py
larpix/zmq_io.py

I think it's been long enough. I've been using this branch with no issues so far.

V2.0.0 rc.1 bugfixes

---

setup.py

Add version numbers to the package dependencies in setup.py

Update setup.py dependencies to include version numbers (#105)

---

README.md

Add a simple example for running with the Bern DAQ board.
Update the CI badge.
This is mostly just a check that the CI is run automatically.

Test PR: Update README

---

.travis.yml

I think this will work but it's hard to test deployments...

Add automatic deployment to pypi (#128)

---

larpix/configs/chip/quiet.json

Update quiet.json config to enable periodic reset

---

larpix/io/multizmq_io.py

Add MultiZMQ_IO cleanup method

---

CONTRIBUTING.md

This file describes our branch workflow and how to contact us.

Create a CONTRIBUTING.md file

---

larpix/format/message_format.py

Update message_format.py docstrings

---

larpix/configs/controller/__init__.py

Update controller config docs to reflect new format

---

larpix/io/multizmq_io.py

Parse packets at the end of empty_queue loop

---

setup.py

Has not been needed for a long time

Remove larpix-geometry as a dependency

---

setup.py

Fix package_data dict format in setup.py

---

larpix/configs/controller/network-3x3-tile-channel0.json
larpix/configs/controller/network-3x3-tile-channel1.json
larpix/configs/controller/network-3x3-tile-channel2.json
larpix/controller.py
scripts/gen_hydra_simple.py

Also includes some minor changes in the gen_hydra_network script to account for modifications to controller network config files.

Create network configs for 3x3 tile
